<?php
/**
 * @file
 * Code for the teia_natural_valley feature.
 */

include_once 'teia_natural_valley.features.inc';

/**
 * Implements hook_block_info().
 */
function teia_natural_valley_block_info() {
  $blocks = array();
  $blocks['teia_donate_now'] = array(
    'info' => t('自然谷: 募款鍵'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['teia_footer'] = array(
    'info' => t('自然谷: 頁尾'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function teia_natural_valley_block_view($delta = '') {
  if ($delta === 'teia_donate_now') {
    return array(
      'subject' => '<none>',
      'content' => '<div><a href="https://e-info.neticrm.tw/civicrm/contribute/transact?reset=1&amp;id=67" id="donate-now" target="_blank"></a></div>',
    );
  } else if ($delta === 'teia_footer') {
    $block_path = drupal_lookup_path("source", "block/natural-valley/footer");
    $block_node = menu_get_object("node", 1, $block_path);
    $block_body = field_get_items('node', $block_node, 'body');
    return array(
      'subject' => '<none>',
      'content' => $block_body[0]['value'],
    );
  }
}
