<?php
/**
 * @file
 * Code for the teia_natural_valley feature.
 */

include_once 'teia_natural_valley.features.inc';

/**
 * Implements hook_block_info().
 */
function teia_natural_valley_block_info() {
  $blocks = array();
  $blocks['teia_donate_now'] = array(
    'info' => t('自然谷募款鍵'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function teia_natural_valley_block_view($delta = '') {
  if ($delta === 'teia_donate_now') {
    return array(
      'subject' => '<none>',
      'content' => '<div><a href="https://e-info.neticrm.tw/civicrm/contribute/transact?reset=1&amp;id=67" id="donate-now" target="_blank"></a></div>',
    );
  }
}
