<?php

function teia_language_language_negotiation_info_alter(&$language_providers)
{
  $language_provider[LOCALE_LANGUAGE_NEGOTIATION_URL]['callbacks']['url_rewrite'] = 'teia_language_url_rewrite_url';
}

function teia_language_url_rewrite_url(&$path, &$options)
{
  $language = _teia_language_get_language($options);
  if ($language->language === language_default()->language) {
    return;
  }
  locale_language_url_rewrite_url();
}

function _teia_language_get_language(&$options)
{
  static $drupal_static_fast;
  if (!isset($drupal_static_fast)) {
    $drupal_static_fast ['languages'] = &drupal_static(__FUNCTION__);
  }
  $languages = &$drupal_static_fast ['languages'];

  if (!isset($languages)) {
    $languages = language_list('enabled');
    $languages = array_flip(array_keys($languages [1]));
  }

  // Language can be passed as an option, or we go for current URL language.
  if (!isset($options ['language'])) {
    global $language_url;
    $options ['language'] = $language_url;
  }
  // We allow only enabled languages here.
  elseif (!isset($languages [$options ['language']->language])) {
    unset($options ['language']);
    return;
  }

  return $options['language'];
}
