<?php
/**
 * @file
 * Code for the teia_natural_valley feature.
 */

include_once 'teia_natural_valley.features.inc';

/**
 * Implements hook_block_info().
 */
function teia_natural_valley_block_info() {
  $blocks = array();
  $blocks['teia_donate_now'] = array(
    'info' => t('自然谷: 募款鍵'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['teia_footer_right'] = array(
    'info' => t('自然谷: 頁尾: 右'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['teia_footer_left'] = array(
    'info' => t('自然谷: 頁尾: 左'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['support'] = array(
    'info' => t('支持我們'),
    //'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

function teia_natural_valley_node_content($path)
{
  $block_path = drupal_lookup_path("source", $path);
  $block_node = menu_get_object("node", 1, $block_path);
  $content = '';
  if ($block_node) {
    $block_body = field_get_items("node", $block_node, "body");
    $content = $block_body[0]['value'];
  }
  return $content;
}

/**
 * Implements hook_block_view().
 */
function teia_natural_valley_block_view($delta = '') {
  if ($delta === 'teia_donate_now') {
    return array(
      'subject' => '',
      'content' => '<div><a href="https://e-info.neticrm.tw/civicrm/contribute/transact?reset=1&amp;id=67" id="donate-now" target="_blank"></a></div>',
    );
  } else if ($delta === 'teia_footer_left') {
    return array(
      'subject' => '',
      'content' => teia_natural_valley_node_content('block/natural-valley/footer-left'),
    );
  } else if ($delta === 'teia_footer_right') {
    return array(
      'subject' => '',
      'content' => teia_natural_valley_node_content('block/natural-valley/footer-right'),
    );
  } else if ($delta === 'support') {
    $config = array(
      'menu_name' => 'menu-content-menu',
      'parent_mlid' => 3014,
      'title_link' => FALSE,
      'admin_title' => '自然谷: 支持我們',
      'level' => 1,
      'follow' => 0,
      'depth' => 1,
      'expanded' => TRUE,
      'sort' => FALSE,
    );
    $menu = menu_tree_build($config);
    unset($menu['subject']);
    unset($menu['subject_array']);
    $output = array(
      'subject' => t('支持自然谷'),
      'content' => array(
        'pretext' => array(
          '#type' => 'markup',
          '#markup' => teia_natural_valley_node_content('natural-valley/support'),
        ),
        'menu' => $menu,
      )
    );
    return $output;
  }
}

/**
 * Implements hook_menu_block_get_menus()
 */
function teia_natural_valley_menu_block_get_menus() {
  $menus = array();
  $menus['teia-natural-valley-join'] = '加入我們';
  return $menus;
}

/**
 * Implements hook_menu_block_blocks()
 */
function teia_natural_valley_menu_block_blocks() {
  return array(
    'teia-natural-valley-join' => array(
      'menu_name' => 'menu-content-menu',
      'parent_mlid' => 6476,
      'title_link' => FALSE,
      'admin_title' => '自然谷: 加入我們',
      'level' => 1,
      'follow' => 0,
      'depth' => 1,
      'expanded' => TRUE,
      'sort' => FALSE,
    ),
  );
}

